/* This file was automatically generated by CasADi 3.6.4.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

int mwv1_left_vogel(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int mwv1_left_vogel_alloc_mem(void);
int mwv1_left_vogel_init_mem(int mem);
void mwv1_left_vogel_free_mem(int mem);
int mwv1_left_vogel_checkout(void);
void mwv1_left_vogel_release(int mem);
void mwv1_left_vogel_incref(void);
void mwv1_left_vogel_decref(void);
casadi_int mwv1_left_vogel_n_in(void);
casadi_int mwv1_left_vogel_n_out(void);
casadi_real mwv1_left_vogel_default_in(casadi_int i);
const char* mwv1_left_vogel_name_in(casadi_int i);
const char* mwv1_left_vogel_name_out(casadi_int i);
const casadi_int* mwv1_left_vogel_sparsity_in(casadi_int i);
const casadi_int* mwv1_left_vogel_sparsity_out(casadi_int i);
int mwv1_left_vogel_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define mwv1_left_vogel_SZ_ARG 2
#define mwv1_left_vogel_SZ_RES 2
#define mwv1_left_vogel_SZ_IW 0
#define mwv1_left_vogel_SZ_W 20
int mwv1_left_pi(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int mwv1_left_pi_alloc_mem(void);
int mwv1_left_pi_init_mem(int mem);
void mwv1_left_pi_free_mem(int mem);
int mwv1_left_pi_checkout(void);
void mwv1_left_pi_release(int mem);
void mwv1_left_pi_incref(void);
void mwv1_left_pi_decref(void);
casadi_int mwv1_left_pi_n_in(void);
casadi_int mwv1_left_pi_n_out(void);
casadi_real mwv1_left_pi_default_in(casadi_int i);
const char* mwv1_left_pi_name_in(casadi_int i);
const char* mwv1_left_pi_name_out(casadi_int i);
const casadi_int* mwv1_left_pi_sparsity_in(casadi_int i);
const casadi_int* mwv1_left_pi_sparsity_out(casadi_int i);
int mwv1_left_pi_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define mwv1_left_pi_SZ_ARG 2
#define mwv1_left_pi_SZ_RES 2
#define mwv1_left_pi_SZ_IW 0
#define mwv1_left_pi_SZ_W 16
int mwv1_closure(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int mwv1_closure_alloc_mem(void);
int mwv1_closure_init_mem(int mem);
void mwv1_closure_free_mem(int mem);
int mwv1_closure_checkout(void);
void mwv1_closure_release(int mem);
void mwv1_closure_incref(void);
void mwv1_closure_decref(void);
casadi_int mwv1_closure_n_in(void);
casadi_int mwv1_closure_n_out(void);
casadi_real mwv1_closure_default_in(casadi_int i);
const char* mwv1_closure_name_in(casadi_int i);
const char* mwv1_closure_name_out(casadi_int i);
const casadi_int* mwv1_closure_sparsity_in(casadi_int i);
const casadi_int* mwv1_closure_sparsity_out(casadi_int i);
int mwv1_closure_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define mwv1_closure_SZ_ARG 2
#define mwv1_closure_SZ_RES 2
#define mwv1_closure_SZ_IW 0
#define mwv1_closure_SZ_W 72
int mwv1_cell(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int mwv1_cell_alloc_mem(void);
int mwv1_cell_init_mem(int mem);
void mwv1_cell_free_mem(int mem);
int mwv1_cell_checkout(void);
void mwv1_cell_release(int mem);
void mwv1_cell_incref(void);
void mwv1_cell_decref(void);
casadi_int mwv1_cell_n_in(void);
casadi_int mwv1_cell_n_out(void);
casadi_real mwv1_cell_default_in(casadi_int i);
const char* mwv1_cell_name_in(casadi_int i);
const char* mwv1_cell_name_out(casadi_int i);
const casadi_int* mwv1_cell_sparsity_in(casadi_int i);
const casadi_int* mwv1_cell_sparsity_out(casadi_int i);
int mwv1_cell_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define mwv1_cell_SZ_ARG 5
#define mwv1_cell_SZ_RES 3
#define mwv1_cell_SZ_IW 0
#define mwv1_cell_SZ_W 46
int mwv1_choke_simpson_linear(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int mwv1_choke_simpson_linear_alloc_mem(void);
int mwv1_choke_simpson_linear_init_mem(int mem);
void mwv1_choke_simpson_linear_free_mem(int mem);
int mwv1_choke_simpson_linear_checkout(void);
void mwv1_choke_simpson_linear_release(int mem);
void mwv1_choke_simpson_linear_incref(void);
void mwv1_choke_simpson_linear_decref(void);
casadi_int mwv1_choke_simpson_linear_n_in(void);
casadi_int mwv1_choke_simpson_linear_n_out(void);
casadi_real mwv1_choke_simpson_linear_default_in(casadi_int i);
const char* mwv1_choke_simpson_linear_name_in(casadi_int i);
const char* mwv1_choke_simpson_linear_name_out(casadi_int i);
const casadi_int* mwv1_choke_simpson_linear_sparsity_in(casadi_int i);
const casadi_int* mwv1_choke_simpson_linear_sparsity_out(casadi_int i);
int mwv1_choke_simpson_linear_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define mwv1_choke_simpson_linear_SZ_ARG 2
#define mwv1_choke_simpson_linear_SZ_RES 2
#define mwv1_choke_simpson_linear_SZ_IW 0
#define mwv1_choke_simpson_linear_SZ_W 35
int mwv1_choke_simpson_sigmoid(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int mwv1_choke_simpson_sigmoid_alloc_mem(void);
int mwv1_choke_simpson_sigmoid_init_mem(int mem);
void mwv1_choke_simpson_sigmoid_free_mem(int mem);
int mwv1_choke_simpson_sigmoid_checkout(void);
void mwv1_choke_simpson_sigmoid_release(int mem);
void mwv1_choke_simpson_sigmoid_incref(void);
void mwv1_choke_simpson_sigmoid_decref(void);
casadi_int mwv1_choke_simpson_sigmoid_n_in(void);
casadi_int mwv1_choke_simpson_sigmoid_n_out(void);
casadi_real mwv1_choke_simpson_sigmoid_default_in(casadi_int i);
const char* mwv1_choke_simpson_sigmoid_name_in(casadi_int i);
const char* mwv1_choke_simpson_sigmoid_name_out(casadi_int i);
const casadi_int* mwv1_choke_simpson_sigmoid_sparsity_in(casadi_int i);
const casadi_int* mwv1_choke_simpson_sigmoid_sparsity_out(casadi_int i);
int mwv1_choke_simpson_sigmoid_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define mwv1_choke_simpson_sigmoid_SZ_ARG 2
#define mwv1_choke_simpson_sigmoid_SZ_RES 2
#define mwv1_choke_simpson_sigmoid_SZ_IW 0
#define mwv1_choke_simpson_sigmoid_SZ_W 35
int mwv1_choke_simpson_convex(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int mwv1_choke_simpson_convex_alloc_mem(void);
int mwv1_choke_simpson_convex_init_mem(int mem);
void mwv1_choke_simpson_convex_free_mem(int mem);
int mwv1_choke_simpson_convex_checkout(void);
void mwv1_choke_simpson_convex_release(int mem);
void mwv1_choke_simpson_convex_incref(void);
void mwv1_choke_simpson_convex_decref(void);
casadi_int mwv1_choke_simpson_convex_n_in(void);
casadi_int mwv1_choke_simpson_convex_n_out(void);
casadi_real mwv1_choke_simpson_convex_default_in(casadi_int i);
const char* mwv1_choke_simpson_convex_name_in(casadi_int i);
const char* mwv1_choke_simpson_convex_name_out(casadi_int i);
const casadi_int* mwv1_choke_simpson_convex_sparsity_in(casadi_int i);
const casadi_int* mwv1_choke_simpson_convex_sparsity_out(casadi_int i);
int mwv1_choke_simpson_convex_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define mwv1_choke_simpson_convex_SZ_ARG 2
#define mwv1_choke_simpson_convex_SZ_RES 2
#define mwv1_choke_simpson_convex_SZ_IW 0
#define mwv1_choke_simpson_convex_SZ_W 35
int mwv1_choke_simpson_concave(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int mwv1_choke_simpson_concave_alloc_mem(void);
int mwv1_choke_simpson_concave_init_mem(int mem);
void mwv1_choke_simpson_concave_free_mem(int mem);
int mwv1_choke_simpson_concave_checkout(void);
void mwv1_choke_simpson_concave_release(int mem);
void mwv1_choke_simpson_concave_incref(void);
void mwv1_choke_simpson_concave_decref(void);
casadi_int mwv1_choke_simpson_concave_n_in(void);
casadi_int mwv1_choke_simpson_concave_n_out(void);
casadi_real mwv1_choke_simpson_concave_default_in(casadi_int i);
const char* mwv1_choke_simpson_concave_name_in(casadi_int i);
const char* mwv1_choke_simpson_concave_name_out(casadi_int i);
const casadi_int* mwv1_choke_simpson_concave_sparsity_in(casadi_int i);
const casadi_int* mwv1_choke_simpson_concave_sparsity_out(casadi_int i);
int mwv1_choke_simpson_concave_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define mwv1_choke_simpson_concave_SZ_ARG 2
#define mwv1_choke_simpson_concave_SZ_RES 2
#define mwv1_choke_simpson_concave_SZ_IW 0
#define mwv1_choke_simpson_concave_SZ_W 35
int mwv1_choke_bernoulli_linear(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int mwv1_choke_bernoulli_linear_alloc_mem(void);
int mwv1_choke_bernoulli_linear_init_mem(int mem);
void mwv1_choke_bernoulli_linear_free_mem(int mem);
int mwv1_choke_bernoulli_linear_checkout(void);
void mwv1_choke_bernoulli_linear_release(int mem);
void mwv1_choke_bernoulli_linear_incref(void);
void mwv1_choke_bernoulli_linear_decref(void);
casadi_int mwv1_choke_bernoulli_linear_n_in(void);
casadi_int mwv1_choke_bernoulli_linear_n_out(void);
casadi_real mwv1_choke_bernoulli_linear_default_in(casadi_int i);
const char* mwv1_choke_bernoulli_linear_name_in(casadi_int i);
const char* mwv1_choke_bernoulli_linear_name_out(casadi_int i);
const casadi_int* mwv1_choke_bernoulli_linear_sparsity_in(casadi_int i);
const casadi_int* mwv1_choke_bernoulli_linear_sparsity_out(casadi_int i);
int mwv1_choke_bernoulli_linear_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define mwv1_choke_bernoulli_linear_SZ_ARG 2
#define mwv1_choke_bernoulli_linear_SZ_RES 2
#define mwv1_choke_bernoulli_linear_SZ_IW 0
#define mwv1_choke_bernoulli_linear_SZ_W 24
int mwv1_choke_bernoulli_sigmoid(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int mwv1_choke_bernoulli_sigmoid_alloc_mem(void);
int mwv1_choke_bernoulli_sigmoid_init_mem(int mem);
void mwv1_choke_bernoulli_sigmoid_free_mem(int mem);
int mwv1_choke_bernoulli_sigmoid_checkout(void);
void mwv1_choke_bernoulli_sigmoid_release(int mem);
void mwv1_choke_bernoulli_sigmoid_incref(void);
void mwv1_choke_bernoulli_sigmoid_decref(void);
casadi_int mwv1_choke_bernoulli_sigmoid_n_in(void);
casadi_int mwv1_choke_bernoulli_sigmoid_n_out(void);
casadi_real mwv1_choke_bernoulli_sigmoid_default_in(casadi_int i);
const char* mwv1_choke_bernoulli_sigmoid_name_in(casadi_int i);
const char* mwv1_choke_bernoulli_sigmoid_name_out(casadi_int i);
const casadi_int* mwv1_choke_bernoulli_sigmoid_sparsity_in(casadi_int i);
const casadi_int* mwv1_choke_bernoulli_sigmoid_sparsity_out(casadi_int i);
int mwv1_choke_bernoulli_sigmoid_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define mwv1_choke_bernoulli_sigmoid_SZ_ARG 2
#define mwv1_choke_bernoulli_sigmoid_SZ_RES 2
#define mwv1_choke_bernoulli_sigmoid_SZ_IW 0
#define mwv1_choke_bernoulli_sigmoid_SZ_W 24
int mwv1_choke_bernoulli_convex(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int mwv1_choke_bernoulli_convex_alloc_mem(void);
int mwv1_choke_bernoulli_convex_init_mem(int mem);
void mwv1_choke_bernoulli_convex_free_mem(int mem);
int mwv1_choke_bernoulli_convex_checkout(void);
void mwv1_choke_bernoulli_convex_release(int mem);
void mwv1_choke_bernoulli_convex_incref(void);
void mwv1_choke_bernoulli_convex_decref(void);
casadi_int mwv1_choke_bernoulli_convex_n_in(void);
casadi_int mwv1_choke_bernoulli_convex_n_out(void);
casadi_real mwv1_choke_bernoulli_convex_default_in(casadi_int i);
const char* mwv1_choke_bernoulli_convex_name_in(casadi_int i);
const char* mwv1_choke_bernoulli_convex_name_out(casadi_int i);
const casadi_int* mwv1_choke_bernoulli_convex_sparsity_in(casadi_int i);
const casadi_int* mwv1_choke_bernoulli_convex_sparsity_out(casadi_int i);
int mwv1_choke_bernoulli_convex_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define mwv1_choke_bernoulli_convex_SZ_ARG 2
#define mwv1_choke_bernoulli_convex_SZ_RES 2
#define mwv1_choke_bernoulli_convex_SZ_IW 0
#define mwv1_choke_bernoulli_convex_SZ_W 24
int mwv1_choke_bernoulli_concave(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int mwv1_choke_bernoulli_concave_alloc_mem(void);
int mwv1_choke_bernoulli_concave_init_mem(int mem);
void mwv1_choke_bernoulli_concave_free_mem(int mem);
int mwv1_choke_bernoulli_concave_checkout(void);
void mwv1_choke_bernoulli_concave_release(int mem);
void mwv1_choke_bernoulli_concave_incref(void);
void mwv1_choke_bernoulli_concave_decref(void);
casadi_int mwv1_choke_bernoulli_concave_n_in(void);
casadi_int mwv1_choke_bernoulli_concave_n_out(void);
casadi_real mwv1_choke_bernoulli_concave_default_in(casadi_int i);
const char* mwv1_choke_bernoulli_concave_name_in(casadi_int i);
const char* mwv1_choke_bernoulli_concave_name_out(casadi_int i);
const casadi_int* mwv1_choke_bernoulli_concave_sparsity_in(casadi_int i);
const casadi_int* mwv1_choke_bernoulli_concave_sparsity_out(casadi_int i);
int mwv1_choke_bernoulli_concave_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define mwv1_choke_bernoulli_concave_SZ_ARG 2
#define mwv1_choke_bernoulli_concave_SZ_RES 2
#define mwv1_choke_bernoulli_concave_SZ_IW 0
#define mwv1_choke_bernoulli_concave_SZ_W 24
#ifdef __cplusplus
} /* extern "C" */
#endif
