/* This file was automatically generated by CasADi 3.6.4.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) manywells_v1_residual_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_f10 CASADI_PREFIX(f10)
#define casadi_f11 CASADI_PREFIX(f11)
#define casadi_f2 CASADI_PREFIX(f2)
#define casadi_f3 CASADI_PREFIX(f3)
#define casadi_f4 CASADI_PREFIX(f4)
#define casadi_f5 CASADI_PREFIX(f5)
#define casadi_f6 CASADI_PREFIX(f6)
#define casadi_f7 CASADI_PREFIX(f7)
#define casadi_f8 CASADI_PREFIX(f8)
#define casadi_f9 CASADI_PREFIX(f9)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[11] = {7, 1, 0, 7, 0, 1, 2, 3, 4, 5, 6};
static const casadi_int casadi_s1[23] = {19, 1, 0, 19, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18};
static const casadi_int casadi_s2[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s3[31] = {3, 7, 0, 3, 6, 9, 12, 15, 18, 21, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2};
static const casadi_int casadi_s4[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s5[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s6[38] = {4, 7, 0, 4, 8, 12, 16, 20, 24, 28, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3};
static const casadi_int casadi_s7[17] = {1, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 0, 0, 0, 0, 0, 0};

/* mwv1_left_vogel:(x[7],P[19])->(g[3],J_x[3x7]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a3, a4, a5, a6, a7, a8, a9;
  a0=3.1415926535897931e+00;
  a1=arg[1]? arg[1][1] : 0;
  a2=2.;
  a3=(a1/a2);
  a3=casadi_sq(a3);
  a3=(a0*a3);
  a4=arg[0]? arg[0][3] : 0;
  a5=(a3*a4);
  a6=arg[0]? arg[0][4] : 0;
  a7=(a5*a6);
  a8=arg[0]? arg[0][1] : 0;
  a9=(a7*a8);
  a10=arg[1]? arg[1][10] : 0;
  a11=1.;
  a12=(a11-a10);
  a10=(a10/a12);
  a12=arg[1]? arg[1][8] : 0;
  a13=2.0000000000000001e-01;
  a14=arg[0]? arg[0][0] : 0;
  a15=arg[1]? arg[1][13] : 0;
  a14=(a14/a15);
  a16=(a13*a14);
  a16=(a11-a16);
  a17=8.0000000000000004e-01;
  a18=casadi_sq(a14);
  a18=(a17*a18);
  a16=(a16-a18);
  a16=(a12*a16);
  a18=(a10*a16);
  a19=arg[1]? arg[1][18] : 0;
  a18=(a18+a19);
  a9=(a9-a18);
  if (res[0]!=0) res[0][0]=a9;
  a1=(a1/a2);
  a1=casadi_sq(a1);
  a0=(a0*a1);
  a4=(a11-a4);
  a4=(a0*a4);
  a1=arg[0]? arg[0][5] : 0;
  a2=(a4*a1);
  a9=arg[0]? arg[0][2] : 0;
  a18=(a2*a9);
  a18=(a18-a16);
  if (res[0]!=0) res[0][1]=a18;
  a18=arg[0]? arg[0][6] : 0;
  a16=arg[1]? arg[1][15] : 0;
  a18=(a18-a16);
  if (res[0]!=0) res[0][2]=a18;
  a13=(a13/a15);
  a14=(a14+a14);
  a14=(a14/a15);
  a17=(a17*a14);
  a13=(a13+a17);
  a12=(a12*a13);
  a10=(a10*a12);
  if (res[1]!=0) res[1][0]=a10;
  if (res[1]!=0) res[1][1]=a12;
  a12=0.;
  if (res[1]!=0) res[1][2]=a12;
  if (res[1]!=0) res[1][3]=a7;
  if (res[1]!=0) res[1][4]=a12;
  if (res[1]!=0) res[1][5]=a12;
  if (res[1]!=0) res[1][6]=a12;
  if (res[1]!=0) res[1][7]=a2;
  if (res[1]!=0) res[1][8]=a12;
  a6=(a6*a3);
  a6=(a8*a6);
  if (res[1]!=0) res[1][9]=a6;
  a1=(a1*a0);
  a1=(a9*a1);
  a1=(-a1);
  if (res[1]!=0) res[1][10]=a1;
  if (res[1]!=0) res[1][11]=a12;
  a8=(a8*a5);
  if (res[1]!=0) res[1][12]=a8;
  if (res[1]!=0) res[1][13]=a12;
  if (res[1]!=0) res[1][14]=a12;
  if (res[1]!=0) res[1][15]=a12;
  a9=(a9*a4);
  if (res[1]!=0) res[1][16]=a9;
  if (res[1]!=0) res[1][17]=a12;
  if (res[1]!=0) res[1][18]=a12;
  if (res[1]!=0) res[1][19]=a12;
  if (res[1]!=0) res[1][20]=a11;
  return 0;
}

CASADI_SYMBOL_EXPORT int mwv1_left_vogel(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int mwv1_left_vogel_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int mwv1_left_vogel_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void mwv1_left_vogel_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int mwv1_left_vogel_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void mwv1_left_vogel_release(int mem) {
}

CASADI_SYMBOL_EXPORT void mwv1_left_vogel_incref(void) {
}

CASADI_SYMBOL_EXPORT void mwv1_left_vogel_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int mwv1_left_vogel_n_in(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_int mwv1_left_vogel_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real mwv1_left_vogel_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* mwv1_left_vogel_name_in(casadi_int i) {
  switch (i) {
    case 0: return "x";
    case 1: return "P";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* mwv1_left_vogel_name_out(casadi_int i) {
  switch (i) {
    case 0: return "g";
    case 1: return "J_x";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* mwv1_left_vogel_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* mwv1_left_vogel_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    case 1: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int mwv1_left_vogel_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* mwv1_left_pi:(x[7],P[19])->(g[3],J_x[3x7]) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a2, a3, a4, a5, a6, a7, a8, a9;
  a0=3.1415926535897931e+00;
  a1=arg[1]? arg[1][1] : 0;
  a2=2.;
  a3=(a1/a2);
  a3=casadi_sq(a3);
  a3=(a0*a3);
  a4=arg[0]? arg[0][3] : 0;
  a5=(a3*a4);
  a6=arg[0]? arg[0][4] : 0;
  a7=(a5*a6);
  a8=arg[0]? arg[0][1] : 0;
  a9=(a7*a8);
  a10=arg[1]? arg[1][10] : 0;
  a11=1.;
  a12=(a11-a10);
  a10=(a10/a12);
  a12=arg[1]? arg[1][9] : 0;
  a13=arg[1]? arg[1][13] : 0;
  a14=arg[0]? arg[0][0] : 0;
  a13=(a13-a14);
  a13=(a12*a13);
  a14=(a10*a13);
  a15=arg[1]? arg[1][18] : 0;
  a14=(a14+a15);
  a9=(a9-a14);
  if (res[0]!=0) res[0][0]=a9;
  a1=(a1/a2);
  a1=casadi_sq(a1);
  a0=(a0*a1);
  a4=(a11-a4);
  a4=(a0*a4);
  a1=arg[0]? arg[0][5] : 0;
  a2=(a4*a1);
  a9=arg[0]? arg[0][2] : 0;
  a14=(a2*a9);
  a14=(a14-a13);
  if (res[0]!=0) res[0][1]=a14;
  a14=arg[0]? arg[0][6] : 0;
  a13=arg[1]? arg[1][15] : 0;
  a14=(a14-a13);
  if (res[0]!=0) res[0][2]=a14;
  a10=(a10*a12);
  if (res[1]!=0) res[1][0]=a10;
  if (res[1]!=0) res[1][1]=a12;
  a12=0.;
  if (res[1]!=0) res[1][2]=a12;
  if (res[1]!=0) res[1][3]=a7;
  if (res[1]!=0) res[1][4]=a12;
  if (res[1]!=0) res[1][5]=a12;
  if (res[1]!=0) res[1][6]=a12;
  if (res[1]!=0) res[1][7]=a2;
  if (res[1]!=0) res[1][8]=a12;
  a6=(a6*a3);
  a6=(a8*a6);
  if (res[1]!=0) res[1][9]=a6;
  a1=(a1*a0);
  a1=(a9*a1);
  a1=(-a1);
  if (res[1]!=0) res[1][10]=a1;
  if (res[1]!=0) res[1][11]=a12;
  a8=(a8*a5);
  if (res[1]!=0) res[1][12]=a8;
  if (res[1]!=0) res[1][13]=a12;
  if (res[1]!=0) res[1][14]=a12;
  if (res[1]!=0) res[1][15]=a12;
  a9=(a9*a4);
  if (res[1]!=0) res[1][16]=a9;
  if (res[1]!=0) res[1][17]=a12;
  if (res[1]!=0) res[1][18]=a12;
  if (res[1]!=0) res[1][19]=a12;
  if (res[1]!=0) res[1][20]=a11;
  return 0;
}

CASADI_SYMBOL_EXPORT int mwv1_left_pi(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f1(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int mwv1_left_pi_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int mwv1_left_pi_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void mwv1_left_pi_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int mwv1_left_pi_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void mwv1_left_pi_release(int mem) {
}

CASADI_SYMBOL_EXPORT void mwv1_left_pi_incref(void) {
}

CASADI_SYMBOL_EXPORT void mwv1_left_pi_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int mwv1_left_pi_n_in(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_int mwv1_left_pi_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real mwv1_left_pi_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* mwv1_left_pi_name_in(casadi_int i) {
  switch (i) {
    case 0: return "x";
    case 1: return "P";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* mwv1_left_pi_name_out(casadi_int i) {
  switch (i) {
    case 0: return "g";
    case 1: return "J_x";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* mwv1_left_pi_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* mwv1_left_pi_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    case 1: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int mwv1_left_pi_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* mwv1_closure:(x[7],P[19])->(g[3],J_x[3x7]) */
static int casadi_f2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a4, a40, a41, a42, a43, a44, a45, a46, a47, a48, a49, a5, a50, a51, a52, a53, a54, a55, a56, a57, a58, a59, a6, a60, a61, a62, a63, a64, a65, a66, a67, a68, a69, a7, a70, a71, a8, a9;
  a0=arg[0]? arg[0][1] : 0;
  a1=3.1771525800000000e+00;
  a2=arg[0]? arg[0][3] : 0;
  a3=(a2*a0);
  a4=3.1000000000000001e+00;
  a5=9.8066499999999994e+00;
  a6=1.0000000000000000e-03;
  a7=1.1159100000000000e+00;
  a8=3.0500000000000002e-03;
  a9=arg[0]? arg[0][6] : 0;
  a10=2.7314999999999998e+02;
  a11=(a9-a10);
  a11=(a8*a11);
  a11=(a7-a11);
  a11=(a6*a11);
  a12=3.8085000000000001e+01;
  a13=2.5900000000000001e-01;
  a14=1.4150000000000000e+02;
  a15=arg[0]? arg[0][5] : 0;
  a16=9.9910000000000002e+02;
  a17=(a15/a16);
  a18=(a14/a17);
  a19=1.3150000000000000e+02;
  a20=(a18-a19);
  a20=(a13*a20);
  a20=(a12-a20);
  a21=(a11*a20);
  a21=(a5*a21);
  a22=arg[0]? arg[0][4] : 0;
  a23=(a15-a22);
  a24=(a21*a23);
  a25=casadi_sq(a22);
  a24=(a24/a25);
  a26=2.5000000000000000e-01;
  a27=pow(a24,a26);
  a27=(a4*a27);
  a27=(a3-a27);
  a27=tanh(a27);
  a28=(a1*a27);
  a29=6.8193848900000003e+00;
  a30=2.;
  a31=6.9999999999999996e-01;
  a31=(a2-a31);
  a31=(a30*a31);
  a31=tanh(a31);
  a32=(a29*a31);
  a28=(a28+a32);
  a32=3.0182974000000001e-01;
  a33=1.0800000000000001e+00;
  a34=1.;
  a35=(a34-a2);
  a36=arg[0]? arg[0][2] : 0;
  a37=(a35*a36);
  a37=(a33*a37);
  a3=(a3-a37);
  a3=tanh(a3);
  a37=(a32*a3);
  a28=(a28+a37);
  a37=3.5836246500000000e+00;
  a38=(a2-a26);
  a38=(a30*a38);
  a38=tanh(a38);
  a39=(a37*a38);
  a28=(a28+a39);
  a39=3.9290439099999999e+00;
  a28=(a28-a39);
  a28=exp(a28);
  a39=-1.4797342700000000e+00;
  a40=(a39*a27);
  a41=4.3403331700000001e+00;
  a42=(a41*a31);
  a40=(a40-a42);
  a42=2.5820000599999999e+00;
  a43=(a42*a3);
  a40=(a40+a43);
  a43=3.4965691099999998e+00;
  a44=(a43*a38);
  a40=(a40+a44);
  a44=1.4650947700000001e+00;
  a40=(a40-a44);
  a40=exp(a40);
  a44=(a28+a40);
  a45=-1.6974183000000000e+00;
  a46=(a45*a27);
  a47=2.4790517200000002e+00;
  a48=(a47*a31);
  a46=(a46-a48);
  a48=2.8838298000000000e+00;
  a49=(a48*a3);
  a46=(a46-a49);
  a49=7.0801937600000002e+00;
  a50=(a49*a38);
  a46=(a46-a50);
  a50=5.3941386900000001e+00;
  a46=(a46+a50);
  a46=exp(a46);
  a44=(a44+a46);
  a50=(a28/a44);
  a51=1.1750000000000000e+00;
  a52=(a40/a44);
  a53=(a51*a52);
  a53=(a50+a53);
  a54=1.2000000000000000e+00;
  a55=(a46/a44);
  a56=(a54*a55);
  a53=(a53+a56);
  a56=(a2*a0);
  a57=(a34-a2);
  a58=(a57*a36);
  a56=(a56+a58);
  a58=(a53*a56);
  a58=(a0-a58);
  a59=3.4999999999999998e-01;
  a60=arg[1]? arg[1][1] : 0;
  a60=(a5*a60);
  a61=(a22/a15);
  a62=(a34-a61);
  a62=(a60*a62);
  a62=sqrt(a62);
  a63=(a59*a62);
  a64=(a52*a63);
  a65=1.5300000000000000e+00;
  a10=(a9-a10);
  a10=(a8*a10);
  a7=(a7-a10);
  a7=(a6*a7);
  a16=(a15/a16);
  a14=(a14/a16);
  a19=(a14-a19);
  a19=(a13*a19);
  a12=(a12-a19);
  a19=(a7*a12);
  a19=(a5*a19);
  a10=(a15-a22);
  a66=(a19*a10);
  a67=casadi_sq(a15);
  a66=(a66/a67);
  a68=pow(a66,a26);
  a68=(a65*a68);
  a69=(a55*a68);
  a64=(a64+a69);
  a58=(a58-a64);
  if (res[0]!=0) res[0][0]=a58;
  a58=arg[0]? arg[0][0] : 0;
  a64=arg[1]? arg[1][3] : 0;
  a69=(a22*a64);
  a70=(a69*a9);
  a71=100000.;
  a70=(a70/a71);
  a58=(a58-a70);
  if (res[0]!=0) res[0][1]=a58;
  a58=arg[1]? arg[1][2] : 0;
  a58=(a15-a58);
  if (res[0]!=0) res[0][2]=a58;
  a58=0.;
  if (res[1]!=0) res[1][0]=a58;
  if (res[1]!=0) res[1][1]=a34;
  if (res[1]!=0) res[1][2]=a58;
  a70=(a2*a53);
  a70=(a34-a70);
  a3=casadi_sq(a3);
  a3=(a34-a3);
  a71=(a55/a44);
  a54=(a54*a56);
  a68=(a68+a54);
  a71=(a71*a68);
  a54=(a52/a44);
  a51=(a51*a56);
  a63=(a63+a51);
  a54=(a54*a63);
  a71=(a71+a54);
  a50=(a50/a44);
  a50=(a50*a56);
  a71=(a71+a50);
  a63=(a63/a44);
  a63=(a71-a63);
  a40=(a40*a63);
  a42=(a42*a40);
  a68=(a68/a44);
  a68=(a71-a68);
  a46=(a46*a68);
  a48=(a48*a46);
  a42=(a42-a48);
  a56=(a56/a44);
  a71=(a71-a56);
  a28=(a28*a71);
  a32=(a32*a28);
  a42=(a42+a32);
  a3=(a3*a42);
  a27=casadi_sq(a27);
  a27=(a34-a27);
  a45=(a45*a46);
  a39=(a39*a40);
  a45=(a45+a39);
  a1=(a1*a28);
  a45=(a45+a1);
  a27=(a27*a45);
  a45=(a3+a27);
  a2=(a2*a45);
  a70=(a70+a2);
  if (res[1]!=0) res[1][3]=a70;
  if (res[1]!=0) res[1][4]=a58;
  if (res[1]!=0) res[1][5]=a58;
  a57=(a57*a53);
  a33=(a33*a3);
  a35=(a35*a33);
  a57=(a57+a35);
  a57=(-a57);
  if (res[1]!=0) res[1][6]=a57;
  if (res[1]!=0) res[1][7]=a58;
  if (res[1]!=0) res[1][8]=a58;
  a57=(a36*a53);
  a53=(a0*a53);
  a57=(a57-a53);
  a38=casadi_sq(a38);
  a38=(a34-a38);
  a43=(a43*a40);
  a49=(a49*a46);
  a43=(a43-a49);
  a37=(a37*a28);
  a43=(a43+a37);
  a38=(a38*a43);
  a38=(a30*a38);
  a57=(a57+a38);
  a36=(a36*a33);
  a57=(a57+a36);
  a31=casadi_sq(a31);
  a31=(a34-a31);
  a29=(a29*a28);
  a47=(a47*a46);
  a41=(a41*a40);
  a47=(a47+a41);
  a29=(a29-a47);
  a31=(a31*a29);
  a30=(a30*a31);
  a57=(a57+a30);
  a0=(a0*a45);
  a57=(a57+a0);
  if (res[1]!=0) res[1][9]=a57;
  if (res[1]!=0) res[1][10]=a58;
  if (res[1]!=0) res[1][11]=a58;
  a57=-7.5000000000000000e-01;
  a0=pow(a66,a57);
  a0=(a26*a0);
  a65=(a65*a55);
  a0=(a0*a65);
  a65=(a0/a67);
  a19=(a19*a65);
  a59=(a59*a52);
  a62=(a62+a62);
  a59=(a59/a62);
  a60=(a60*a59);
  a59=(a60/a15);
  a59=(a19+a59);
  a22=(a22+a22);
  a62=(a24/a25);
  a24=pow(a24,a57);
  a26=(a26*a24);
  a4=(a4*a27);
  a26=(a26*a4);
  a62=(a62*a26);
  a22=(a22*a62);
  a59=(a59+a22);
  a26=(a26/a25);
  a21=(a21*a26);
  a59=(a59+a21);
  if (res[1]!=0) res[1][12]=a59;
  a59=-1.0000000000000001e-05;
  a9=(a59*a9);
  a64=(a64*a9);
  if (res[1]!=0) res[1][13]=a64;
  if (res[1]!=0) res[1][14]=a58;
  a64=(a15+a15);
  a66=(a66/a67);
  a66=(a66*a0);
  a64=(a64*a66);
  a64=(a64-a19);
  a19=1.0009008107296567e-03;
  a14=(a14/a16);
  a10=(a10*a65);
  a10=(a5*a10);
  a7=(a7*a10);
  a7=(a13*a7);
  a14=(a14*a7);
  a14=(a19*a14);
  a64=(a64-a14);
  a61=(a61/a15);
  a61=(a61*a60);
  a64=(a64-a61);
  a64=(a64-a21);
  a18=(a18/a17);
  a23=(a23*a26);
  a5=(a5*a23);
  a11=(a11*a5);
  a13=(a13*a11);
  a18=(a18*a13);
  a19=(a19*a18);
  a64=(a64-a19);
  if (res[1]!=0) res[1][15]=a64;
  if (res[1]!=0) res[1][16]=a58;
  if (res[1]!=0) res[1][17]=a34;
  a12=(a12*a10);
  a12=(a6*a12);
  a12=(a8*a12);
  a20=(a20*a5);
  a6=(a6*a20);
  a8=(a8*a6);
  a12=(a12+a8);
  if (res[1]!=0) res[1][18]=a12;
  a59=(a59*a69);
  if (res[1]!=0) res[1][19]=a59;
  if (res[1]!=0) res[1][20]=a58;
  return 0;
}

CASADI_SYMBOL_EXPORT int mwv1_closure(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f2(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int mwv1_closure_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int mwv1_closure_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void mwv1_closure_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int mwv1_closure_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void mwv1_closure_release(int mem) {
}

CASADI_SYMBOL_EXPORT void mwv1_closure_incref(void) {
}

CASADI_SYMBOL_EXPORT void mwv1_closure_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int mwv1_closure_n_in(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_int mwv1_closure_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real mwv1_closure_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* mwv1_closure_name_in(casadi_int i) {
  switch (i) {
    case 0: return "x";
    case 1: return "P";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* mwv1_closure_name_out(casadi_int i) {
  switch (i) {
    case 0: return "g";
    case 1: return "J_x";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* mwv1_closure_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* mwv1_closure_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    case 1: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int mwv1_closure_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* mwv1_cell:(x[7],x_prev[7],i,N,P[19])->(g[4],J_x[4x7],J_x_prev[4x7]) */
static int casadi_f3(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a4, a40, a41, a42, a43, a44, a45, a5, a6, a7, a8, a9;
  a0=arg[0]? arg[0][3] : 0;
  a1=arg[0]? arg[0][4] : 0;
  a2=(a0*a1);
  a3=arg[0]? arg[0][1] : 0;
  a4=(a2*a3);
  a5=arg[1]? arg[1][3] : 0;
  a6=arg[1]? arg[1][4] : 0;
  a7=(a5*a6);
  a8=arg[1]? arg[1][1] : 0;
  a9=(a7*a8);
  a4=(a4-a9);
  if (res[0]!=0) res[0][0]=a4;
  a4=1.;
  a9=(a4-a0);
  a10=arg[0]? arg[0][5] : 0;
  a11=(a9*a10);
  a12=arg[0]? arg[0][2] : 0;
  a13=(a11*a12);
  a14=(a4-a5);
  a15=arg[1]? arg[1][5] : 0;
  a16=(a14*a15);
  a17=arg[1]? arg[1][2] : 0;
  a18=(a16*a17);
  a13=(a13-a18);
  if (res[0]!=0) res[0][1]=a13;
  a13=(a0*a1);
  a18=casadi_sq(a3);
  a19=(a13*a18);
  a20=(a4-a0);
  a21=(a20*a10);
  a22=casadi_sq(a12);
  a23=(a21*a22);
  a19=(a19+a23);
  a23=100000.;
  a19=(a19/a23);
  a24=arg[0]? arg[0][0] : 0;
  a19=(a19+a24);
  a24=(a5*a6);
  a25=casadi_sq(a8);
  a26=(a24*a25);
  a27=(a4-a5);
  a28=(a27*a15);
  a29=casadi_sq(a17);
  a30=(a28*a29);
  a26=(a26+a30);
  a26=(a26/a23);
  a30=arg[1]? arg[1][0] : 0;
  a26=(a26+a30);
  a19=(a19-a26);
  a26=arg[4]? arg[4][0] : 0;
  a30=arg[3]? arg[3][0] : 0;
  a26=(a26/a30);
  a31=arg[4]? arg[4][6] : 0;
  a32=arg[4]? arg[4][1] : 0;
  a31=(a31/a32);
  a33=2.;
  a31=(a31/a33);
  a31=(a26*a31);
  a33=(a0*a1);
  a34=(a4-a0);
  a35=(a34*a10);
  a33=(a33+a35);
  a35=(a31*a33);
  a36=(a0*a3);
  a37=(a4-a0);
  a38=(a37*a12);
  a36=(a36+a38);
  a38=casadi_sq(a36);
  a39=(a35*a38);
  a40=9.8066499999999994e+00;
  a40=(a40*a26);
  a33=(a40*a33);
  a39=(a39+a33);
  a39=(a39/a23);
  a19=(a19+a39);
  if (res[0]!=0) res[0][2]=a19;
  a19=arg[0]? arg[0][6] : 0;
  a39=arg[1]? arg[1][6] : 0;
  a39=(a19-a39);
  a23=4.;
  a23=(a23*a26);
  a26=arg[4]? arg[4][7] : 0;
  a23=(a23*a26);
  a26=arg[4]? arg[4][15] : 0;
  a33=arg[2]? arg[2][0] : 0;
  a41=arg[4]? arg[4][16] : 0;
  a41=(a26-a41);
  a33=(a33*a41);
  a33=(a33/a30);
  a26=(a26-a33);
  a19=(a19-a26);
  a19=(a23*a19);
  a26=arg[4]? arg[4][4] : 0;
  a33=(a26*a0);
  a30=(a33*a1);
  a41=(a30*a3);
  a42=arg[4]? arg[4][5] : 0;
  a43=(a4-a0);
  a43=(a42*a43);
  a44=(a43*a10);
  a45=(a44*a12);
  a41=(a41+a45);
  a41=(a32*a41);
  a19=(a19/a41);
  a39=(a39+a19);
  if (res[0]!=0) res[0][3]=a39;
  a39=0.;
  if (res[1]!=0) res[1][0]=a39;
  if (res[1]!=0) res[1][1]=a39;
  if (res[1]!=0) res[1][2]=a4;
  if (res[1]!=0) res[1][3]=a39;
  if (res[1]!=0) res[1][4]=a2;
  if (res[1]!=0) res[1][5]=a39;
  a2=1.0000000000000001e-05;
  a45=(a3+a3);
  a13=(a13*a45);
  a13=(a2*a13);
  a36=(a36+a36);
  a45=(a36*a0);
  a45=(a35*a45);
  a45=(a2*a45);
  a13=(a13+a45);
  if (res[1]!=0) res[1][6]=a13;
  a19=(a19/a41);
  a30=(a32*a30);
  a30=(a19*a30);
  a30=(-a30);
  if (res[1]!=0) res[1][7]=a30;
  if (res[1]!=0) res[1][8]=a39;
  if (res[1]!=0) res[1][9]=a11;
  a11=(a12+a12);
  a21=(a21*a11);
  a21=(a2*a21);
  a37=(a36*a37);
  a37=(a35*a37);
  a37=(a2*a37);
  a21=(a21+a37);
  if (res[1]!=0) res[1][10]=a21;
  a44=(a32*a44);
  a44=(a19*a44);
  a44=(-a44);
  if (res[1]!=0) res[1][11]=a44;
  a44=(a3*a1);
  if (res[1]!=0) res[1][12]=a44;
  a44=(a12*a10);
  a44=(-a44);
  if (res[1]!=0) res[1][13]=a44;
  a44=(a18*a1);
  a21=(a22*a10);
  a44=(a44-a21);
  a44=(a2*a44);
  a21=(a1-a10);
  a37=(a31*a21);
  a37=(a38*a37);
  a11=(a3-a12);
  a36=(a36*a11);
  a35=(a35*a36);
  a37=(a37+a35);
  a21=(a40*a21);
  a37=(a37+a21);
  a37=(a2*a37);
  a44=(a44+a37);
  if (res[1]!=0) res[1][14]=a44;
  a1=(a1*a26);
  a1=(a3*a1);
  a10=(a10*a42);
  a10=(a12*a10);
  a1=(a1-a10);
  a1=(a32*a1);
  a1=(a19*a1);
  a1=(-a1);
  if (res[1]!=0) res[1][15]=a1;
  a1=(a3*a0);
  if (res[1]!=0) res[1][16]=a1;
  if (res[1]!=0) res[1][17]=a39;
  a18=(a18*a0);
  a18=(a2*a18);
  a1=(a31*a0);
  a1=(a38*a1);
  a0=(a40*a0);
  a1=(a1+a0);
  a1=(a2*a1);
  a18=(a18+a1);
  if (res[1]!=0) res[1][18]=a18;
  a3=(a3*a33);
  a3=(a32*a3);
  a3=(a19*a3);
  a3=(-a3);
  if (res[1]!=0) res[1][19]=a3;
  if (res[1]!=0) res[1][20]=a39;
  a9=(a12*a9);
  if (res[1]!=0) res[1][21]=a9;
  a22=(a22*a20);
  a22=(a2*a22);
  a31=(a31*a34);
  a38=(a38*a31);
  a40=(a40*a34);
  a38=(a38+a40);
  a38=(a2*a38);
  a22=(a22+a38);
  if (res[1]!=0) res[1][22]=a22;
  a12=(a12*a43);
  a32=(a32*a12);
  a19=(a19*a32);
  a19=(-a19);
  if (res[1]!=0) res[1][23]=a19;
  if (res[1]!=0) res[1][24]=a39;
  if (res[1]!=0) res[1][25]=a39;
  if (res[1]!=0) res[1][26]=a39;
  a23=(a23/a41);
  a4=(a4+a23);
  if (res[1]!=0) res[1][27]=a4;
  if (res[2]!=0) res[2][0]=a39;
  if (res[2]!=0) res[2][1]=a39;
  a4=-1.;
  if (res[2]!=0) res[2][2]=a4;
  if (res[2]!=0) res[2][3]=a39;
  a7=(-a7);
  if (res[2]!=0) res[2][4]=a7;
  if (res[2]!=0) res[2][5]=a39;
  a7=(a8+a8);
  a24=(a24*a7);
  a24=(a2*a24);
  a24=(-a24);
  if (res[2]!=0) res[2][6]=a24;
  if (res[2]!=0) res[2][7]=a39;
  if (res[2]!=0) res[2][8]=a39;
  a16=(-a16);
  if (res[2]!=0) res[2][9]=a16;
  a16=(a17+a17);
  a28=(a28*a16);
  a28=(a2*a28);
  a28=(-a28);
  if (res[2]!=0) res[2][10]=a28;
  if (res[2]!=0) res[2][11]=a39;
  a28=(a8*a6);
  a28=(-a28);
  if (res[2]!=0) res[2][12]=a28;
  a28=(a17*a15);
  if (res[2]!=0) res[2][13]=a28;
  a6=(a25*a6);
  a15=(a29*a15);
  a6=(a6-a15);
  a6=(a2*a6);
  a6=(-a6);
  if (res[2]!=0) res[2][14]=a6;
  if (res[2]!=0) res[2][15]=a39;
  a8=(a8*a5);
  a8=(-a8);
  if (res[2]!=0) res[2][16]=a8;
  if (res[2]!=0) res[2][17]=a39;
  a25=(a25*a5);
  a25=(a2*a25);
  a25=(-a25);
  if (res[2]!=0) res[2][18]=a25;
  if (res[2]!=0) res[2][19]=a39;
  if (res[2]!=0) res[2][20]=a39;
  a17=(a17*a14);
  a17=(-a17);
  if (res[2]!=0) res[2][21]=a17;
  a29=(a29*a27);
  a2=(a2*a29);
  a2=(-a2);
  if (res[2]!=0) res[2][22]=a2;
  if (res[2]!=0) res[2][23]=a39;
  if (res[2]!=0) res[2][24]=a39;
  if (res[2]!=0) res[2][25]=a39;
  if (res[2]!=0) res[2][26]=a39;
  if (res[2]!=0) res[2][27]=a4;
  return 0;
}

CASADI_SYMBOL_EXPORT int mwv1_cell(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f3(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int mwv1_cell_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int mwv1_cell_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void mwv1_cell_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int mwv1_cell_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void mwv1_cell_release(int mem) {
}

CASADI_SYMBOL_EXPORT void mwv1_cell_incref(void) {
}

CASADI_SYMBOL_EXPORT void mwv1_cell_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int mwv1_cell_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int mwv1_cell_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real mwv1_cell_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* mwv1_cell_name_in(casadi_int i) {
  switch (i) {
    case 0: return "x";
    case 1: return "x_prev";
    case 2: return "i";
    case 3: return "N";
    case 4: return "P";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* mwv1_cell_name_out(casadi_int i) {
  switch (i) {
    case 0: return "g";
    case 1: return "J_x";
    case 2: return "J_x_prev";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* mwv1_cell_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s4;
    case 3: return casadi_s4;
    case 4: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* mwv1_cell_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    case 1: return casadi_s6;
    case 2: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int mwv1_cell_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* mwv1_choke_simpson_linear:(x[7],P[19])->(g,J_x[1x7]) */
static int casadi_f4(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a34, a4, a5, a6, a7, a8, a9;
  a0=3.1415926535897931e+00;
  a1=arg[1]? arg[1][1] : 0;
  a2=2.;
  a3=(a1/a2);
  a3=casadi_sq(a3);
  a3=(a0*a3);
  a4=arg[0]? arg[0][3] : 0;
  a5=(a3*a4);
  a6=arg[0]? arg[0][4] : 0;
  a7=(a5*a6);
  a8=arg[0]? arg[0][1] : 0;
  a9=(a7*a8);
  a1=(a1/a2);
  a1=casadi_sq(a1);
  a0=(a0*a1);
  a1=1.;
  a4=(a1-a4);
  a4=(a0*a4);
  a10=arg[0]? arg[0][5] : 0;
  a11=(a4*a10);
  a12=arg[0]? arg[0][2] : 0;
  a13=(a11*a12);
  a13=(a9+a13);
  a14=arg[1]? arg[1][11] : 0;
  a15=arg[1]? arg[1][17] : 0;
  a14=(a14*a15);
  a15=(a2*a10);
  a16=100000.;
  a17=arg[0]? arg[0][0] : 0;
  a18=5.0000000000000000e-01;
  a19=arg[1]? arg[1][12] : 0;
  a20=(a19*a17);
  a21=arg[1]? arg[1][14] : 0;
  a22=(a20+a21);
  a20=(a20-a21);
  a21=casadi_sq(a20);
  a23=9.9999999999999995e-07;
  a21=(a21+a23);
  a21=sqrt(a21);
  a22=(a22+a21);
  a22=(a18*a22);
  a17=(a17-a22);
  a17=(a16*a17);
  a22=(a15*a17);
  a9=(a9/a13);
  a23=(a10/a6);
  a24=1.6666666666666666e-01;
  a25=pow(a23,a24);
  a26=(a25-a1);
  a27=(a9*a26);
  a27=(a1+a27);
  a28=casadi_sq(a25);
  a29=casadi_sq(a28);
  a30=(a25*a29);
  a30=(a30-a1);
  a31=(a9*a30);
  a31=(a1+a31);
  a32=(a27*a31);
  a22=(a22/a32);
  a33=sqrt(a22);
  a34=(a14*a33);
  a34=(a13-a34);
  if (res[0]!=0) res[0][0]=a34;
  a20=(a20+a20);
  a33=(a33+a33);
  a14=(a14/a33);
  a33=(a14/a32);
  a15=(a15*a33);
  a16=(a16*a15);
  a18=(a18*a16);
  a21=(a21+a21);
  a21=(a18/a21);
  a20=(a20*a21);
  a20=(a20+a18);
  a19=(a19*a20);
  a19=(a19-a16);
  if (res[1]!=0) res[1][0]=a19;
  a22=(a22/a32);
  a22=(a22*a14);
  a27=(a27*a22);
  a30=(a30*a27);
  a31=(a31*a22);
  a26=(a26*a31);
  a30=(a30+a26);
  a26=(a30/a13);
  a13=(a9/a13);
  a13=(a13*a30);
  a1=(a1-a13);
  a26=(a26+a1);
  a7=(a7*a26);
  if (res[1]!=0) res[1][1]=a7;
  a11=(a11*a1);
  if (res[1]!=0) res[1][2]=a11;
  a8=(a8*a26);
  a26=(a6*a8);
  a3=(a3*a26);
  a12=(a12*a1);
  a10=(a10*a12);
  a0=(a0*a10);
  a3=(a3-a0);
  if (res[1]!=0) res[1][3]=a3;
  a5=(a5*a8);
  a8=(a23/a6);
  a3=-8.3333333333333337e-01;
  a23=pow(a23,a3);
  a24=(a24*a23);
  a27=(a9*a27);
  a29=(a29*a27);
  a23=(a25+a25);
  a28=(a28+a28);
  a25=(a25*a27);
  a28=(a28*a25);
  a23=(a23*a28);
  a29=(a29+a23);
  a9=(a9*a31);
  a29=(a29+a9);
  a24=(a24*a29);
  a8=(a8*a24);
  a5=(a5-a8);
  if (res[1]!=0) res[1][4]=a5;
  a24=(a24/a6);
  a17=(a17*a33);
  a2=(a2*a17);
  a24=(a24-a2);
  a4=(a4*a12);
  a24=(a24+a4);
  if (res[1]!=0) res[1][5]=a24;
  a24=0.;
  if (res[1]!=0) res[1][6]=a24;
  return 0;
}

CASADI_SYMBOL_EXPORT int mwv1_choke_simpson_linear(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f4(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int mwv1_choke_simpson_linear_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int mwv1_choke_simpson_linear_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void mwv1_choke_simpson_linear_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int mwv1_choke_simpson_linear_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void mwv1_choke_simpson_linear_release(int mem) {
}

CASADI_SYMBOL_EXPORT void mwv1_choke_simpson_linear_incref(void) {
}

CASADI_SYMBOL_EXPORT void mwv1_choke_simpson_linear_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int mwv1_choke_simpson_linear_n_in(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_int mwv1_choke_simpson_linear_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real mwv1_choke_simpson_linear_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* mwv1_choke_simpson_linear_name_in(casadi_int i) {
  switch (i) {
    case 0: return "x";
    case 1: return "P";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* mwv1_choke_simpson_linear_name_out(casadi_int i) {
  switch (i) {
    case 0: return "g";
    case 1: return "J_x";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* mwv1_choke_simpson_linear_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* mwv1_choke_simpson_linear_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s7;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int mwv1_choke_simpson_linear_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* mwv1_choke_simpson_sigmoid:(x[7],P[19])->(g,J_x[1x7]) */
static int casadi_f5(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a34, a4, a5, a6, a7, a8, a9;
  a0=3.1415926535897931e+00;
  a1=arg[1]? arg[1][1] : 0;
  a2=2.;
  a3=(a1/a2);
  a3=casadi_sq(a3);
  a3=(a0*a3);
  a4=arg[0]? arg[0][3] : 0;
  a5=(a3*a4);
  a6=arg[0]? arg[0][4] : 0;
  a7=(a5*a6);
  a8=arg[0]? arg[0][1] : 0;
  a9=(a7*a8);
  a1=(a1/a2);
  a1=casadi_sq(a1);
  a0=(a0*a1);
  a1=1.;
  a4=(a1-a4);
  a4=(a0*a4);
  a10=arg[0]? arg[0][5] : 0;
  a11=(a4*a10);
  a12=arg[0]? arg[0][2] : 0;
  a13=(a11*a12);
  a13=(a9+a13);
  a14=arg[1]? arg[1][11] : 0;
  a15=arg[1]? arg[1][17] : 0;
  a16=1.5000000000000000e+00;
  a17=pow(a15,a16);
  a18=pow(a15,a16);
  a15=(a1-a15);
  a15=pow(a15,a16);
  a18=(a18+a15);
  a17=(a17/a18);
  a14=(a14*a17);
  a17=(a2*a10);
  a18=100000.;
  a15=arg[0]? arg[0][0] : 0;
  a16=5.0000000000000000e-01;
  a19=arg[1]? arg[1][12] : 0;
  a20=(a19*a15);
  a21=arg[1]? arg[1][14] : 0;
  a22=(a20+a21);
  a20=(a20-a21);
  a21=casadi_sq(a20);
  a23=9.9999999999999995e-07;
  a21=(a21+a23);
  a21=sqrt(a21);
  a22=(a22+a21);
  a22=(a16*a22);
  a15=(a15-a22);
  a15=(a18*a15);
  a22=(a17*a15);
  a9=(a9/a13);
  a23=(a10/a6);
  a24=1.6666666666666666e-01;
  a25=pow(a23,a24);
  a26=(a25-a1);
  a27=(a9*a26);
  a27=(a1+a27);
  a28=casadi_sq(a25);
  a29=casadi_sq(a28);
  a30=(a25*a29);
  a30=(a30-a1);
  a31=(a9*a30);
  a31=(a1+a31);
  a32=(a27*a31);
  a22=(a22/a32);
  a33=sqrt(a22);
  a34=(a14*a33);
  a34=(a13-a34);
  if (res[0]!=0) res[0][0]=a34;
  a20=(a20+a20);
  a33=(a33+a33);
  a14=(a14/a33);
  a33=(a14/a32);
  a17=(a17*a33);
  a18=(a18*a17);
  a16=(a16*a18);
  a21=(a21+a21);
  a21=(a16/a21);
  a20=(a20*a21);
  a20=(a20+a16);
  a19=(a19*a20);
  a19=(a19-a18);
  if (res[1]!=0) res[1][0]=a19;
  a22=(a22/a32);
  a22=(a22*a14);
  a27=(a27*a22);
  a30=(a30*a27);
  a31=(a31*a22);
  a26=(a26*a31);
  a30=(a30+a26);
  a26=(a30/a13);
  a13=(a9/a13);
  a13=(a13*a30);
  a1=(a1-a13);
  a26=(a26+a1);
  a7=(a7*a26);
  if (res[1]!=0) res[1][1]=a7;
  a11=(a11*a1);
  if (res[1]!=0) res[1][2]=a11;
  a8=(a8*a26);
  a26=(a6*a8);
  a3=(a3*a26);
  a12=(a12*a1);
  a10=(a10*a12);
  a0=(a0*a10);
  a3=(a3-a0);
  if (res[1]!=0) res[1][3]=a3;
  a5=(a5*a8);
  a8=(a23/a6);
  a3=-8.3333333333333337e-01;
  a23=pow(a23,a3);
  a24=(a24*a23);
  a27=(a9*a27);
  a29=(a29*a27);
  a23=(a25+a25);
  a28=(a28+a28);
  a25=(a25*a27);
  a28=(a28*a25);
  a23=(a23*a28);
  a29=(a29+a23);
  a9=(a9*a31);
  a29=(a29+a9);
  a24=(a24*a29);
  a8=(a8*a24);
  a5=(a5-a8);
  if (res[1]!=0) res[1][4]=a5;
  a24=(a24/a6);
  a15=(a15*a33);
  a2=(a2*a15);
  a24=(a24-a2);
  a4=(a4*a12);
  a24=(a24+a4);
  if (res[1]!=0) res[1][5]=a24;
  a24=0.;
  if (res[1]!=0) res[1][6]=a24;
  return 0;
}

CASADI_SYMBOL_EXPORT int mwv1_choke_simpson_sigmoid(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f5(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int mwv1_choke_simpson_sigmoid_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int mwv1_choke_simpson_sigmoid_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void mwv1_choke_simpson_sigmoid_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int mwv1_choke_simpson_sigmoid_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void mwv1_choke_simpson_sigmoid_release(int mem) {
}

CASADI_SYMBOL_EXPORT void mwv1_choke_simpson_sigmoid_incref(void) {
}

CASADI_SYMBOL_EXPORT void mwv1_choke_simpson_sigmoid_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int mwv1_choke_simpson_sigmoid_n_in(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_int mwv1_choke_simpson_sigmoid_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real mwv1_choke_simpson_sigmoid_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* mwv1_choke_simpson_sigmoid_name_in(casadi_int i) {
  switch (i) {
    case 0: return "x";
    case 1: return "P";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* mwv1_choke_simpson_sigmoid_name_out(casadi_int i) {
  switch (i) {
    case 0: return "g";
    case 1: return "J_x";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* mwv1_choke_simpson_sigmoid_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* mwv1_choke_simpson_sigmoid_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s7;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int mwv1_choke_simpson_sigmoid_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* mwv1_choke_simpson_convex:(x[7],P[19])->(g,J_x[1x7]) */
static int casadi_f6(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a34, a4, a5, a6, a7, a8, a9;
  a0=3.1415926535897931e+00;
  a1=arg[1]? arg[1][1] : 0;
  a2=2.;
  a3=(a1/a2);
  a3=casadi_sq(a3);
  a3=(a0*a3);
  a4=arg[0]? arg[0][3] : 0;
  a5=(a3*a4);
  a6=arg[0]? arg[0][4] : 0;
  a7=(a5*a6);
  a8=arg[0]? arg[0][1] : 0;
  a9=(a7*a8);
  a1=(a1/a2);
  a1=casadi_sq(a1);
  a0=(a0*a1);
  a1=1.;
  a4=(a1-a4);
  a4=(a0*a4);
  a10=arg[0]? arg[0][5] : 0;
  a11=(a4*a10);
  a12=arg[0]? arg[0][2] : 0;
  a13=(a11*a12);
  a13=(a9+a13);
  a14=arg[1]? arg[1][11] : 0;
  a15=2.5000000000000000e-01;
  a16=arg[1]? arg[1][17] : 0;
  a15=(a15*a16);
  a17=7.5000000000000000e-01;
  a16=casadi_sq(a16);
  a17=(a17*a16);
  a15=(a15+a17);
  a14=(a14*a15);
  a15=(a2*a10);
  a17=100000.;
  a16=arg[0]? arg[0][0] : 0;
  a18=5.0000000000000000e-01;
  a19=arg[1]? arg[1][12] : 0;
  a20=(a19*a16);
  a21=arg[1]? arg[1][14] : 0;
  a22=(a20+a21);
  a20=(a20-a21);
  a21=casadi_sq(a20);
  a23=9.9999999999999995e-07;
  a21=(a21+a23);
  a21=sqrt(a21);
  a22=(a22+a21);
  a22=(a18*a22);
  a16=(a16-a22);
  a16=(a17*a16);
  a22=(a15*a16);
  a9=(a9/a13);
  a23=(a10/a6);
  a24=1.6666666666666666e-01;
  a25=pow(a23,a24);
  a26=(a25-a1);
  a27=(a9*a26);
  a27=(a1+a27);
  a28=casadi_sq(a25);
  a29=casadi_sq(a28);
  a30=(a25*a29);
  a30=(a30-a1);
  a31=(a9*a30);
  a31=(a1+a31);
  a32=(a27*a31);
  a22=(a22/a32);
  a33=sqrt(a22);
  a34=(a14*a33);
  a34=(a13-a34);
  if (res[0]!=0) res[0][0]=a34;
  a20=(a20+a20);
  a33=(a33+a33);
  a14=(a14/a33);
  a33=(a14/a32);
  a15=(a15*a33);
  a17=(a17*a15);
  a18=(a18*a17);
  a21=(a21+a21);
  a21=(a18/a21);
  a20=(a20*a21);
  a20=(a20+a18);
  a19=(a19*a20);
  a19=(a19-a17);
  if (res[1]!=0) res[1][0]=a19;
  a22=(a22/a32);
  a22=(a22*a14);
  a27=(a27*a22);
  a30=(a30*a27);
  a31=(a31*a22);
  a26=(a26*a31);
  a30=(a30+a26);
  a26=(a30/a13);
  a13=(a9/a13);
  a13=(a13*a30);
  a1=(a1-a13);
  a26=(a26+a1);
  a7=(a7*a26);
  if (res[1]!=0) res[1][1]=a7;
  a11=(a11*a1);
  if (res[1]!=0) res[1][2]=a11;
  a8=(a8*a26);
  a26=(a6*a8);
  a3=(a3*a26);
  a12=(a12*a1);
  a10=(a10*a12);
  a0=(a0*a10);
  a3=(a3-a0);
  if (res[1]!=0) res[1][3]=a3;
  a5=(a5*a8);
  a8=(a23/a6);
  a3=-8.3333333333333337e-01;
  a23=pow(a23,a3);
  a24=(a24*a23);
  a27=(a9*a27);
  a29=(a29*a27);
  a23=(a25+a25);
  a28=(a28+a28);
  a25=(a25*a27);
  a28=(a28*a25);
  a23=(a23*a28);
  a29=(a29+a23);
  a9=(a9*a31);
  a29=(a29+a9);
  a24=(a24*a29);
  a8=(a8*a24);
  a5=(a5-a8);
  if (res[1]!=0) res[1][4]=a5;
  a24=(a24/a6);
  a16=(a16*a33);
  a2=(a2*a16);
  a24=(a24-a2);
  a4=(a4*a12);
  a24=(a24+a4);
  if (res[1]!=0) res[1][5]=a24;
  a24=0.;
  if (res[1]!=0) res[1][6]=a24;
  return 0;
}

CASADI_SYMBOL_EXPORT int mwv1_choke_simpson_convex(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f6(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int mwv1_choke_simpson_convex_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int mwv1_choke_simpson_convex_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void mwv1_choke_simpson_convex_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int mwv1_choke_simpson_convex_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void mwv1_choke_simpson_convex_release(int mem) {
}

CASADI_SYMBOL_EXPORT void mwv1_choke_simpson_convex_incref(void) {
}

CASADI_SYMBOL_EXPORT void mwv1_choke_simpson_convex_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int mwv1_choke_simpson_convex_n_in(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_int mwv1_choke_simpson_convex_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real mwv1_choke_simpson_convex_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* mwv1_choke_simpson_convex_name_in(casadi_int i) {
  switch (i) {
    case 0: return "x";
    case 1: return "P";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* mwv1_choke_simpson_convex_name_out(casadi_int i) {
  switch (i) {
    case 0: return "g";
    case 1: return "J_x";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* mwv1_choke_simpson_convex_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* mwv1_choke_simpson_convex_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s7;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int mwv1_choke_simpson_convex_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* mwv1_choke_simpson_concave:(x[7],P[19])->(g,J_x[1x7]) */
static int casadi_f7(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a34, a4, a5, a6, a7, a8, a9;
  a0=3.1415926535897931e+00;
  a1=arg[1]? arg[1][1] : 0;
  a2=2.;
  a3=(a1/a2);
  a3=casadi_sq(a3);
  a3=(a0*a3);
  a4=arg[0]? arg[0][3] : 0;
  a5=(a3*a4);
  a6=arg[0]? arg[0][4] : 0;
  a7=(a5*a6);
  a8=arg[0]? arg[0][1] : 0;
  a9=(a7*a8);
  a1=(a1/a2);
  a1=casadi_sq(a1);
  a0=(a0*a1);
  a1=1.;
  a4=(a1-a4);
  a4=(a0*a4);
  a10=arg[0]? arg[0][5] : 0;
  a11=(a4*a10);
  a12=arg[0]? arg[0][2] : 0;
  a13=(a11*a12);
  a13=(a9+a13);
  a14=arg[1]? arg[1][11] : 0;
  a15=arg[1]? arg[1][17] : 0;
  a16=7.5000000000000000e-01;
  a15=pow(a15,a16);
  a14=(a14*a15);
  a15=(a2*a10);
  a16=100000.;
  a17=arg[0]? arg[0][0] : 0;
  a18=5.0000000000000000e-01;
  a19=arg[1]? arg[1][12] : 0;
  a20=(a19*a17);
  a21=arg[1]? arg[1][14] : 0;
  a22=(a20+a21);
  a20=(a20-a21);
  a21=casadi_sq(a20);
  a23=9.9999999999999995e-07;
  a21=(a21+a23);
  a21=sqrt(a21);
  a22=(a22+a21);
  a22=(a18*a22);
  a17=(a17-a22);
  a17=(a16*a17);
  a22=(a15*a17);
  a9=(a9/a13);
  a23=(a10/a6);
  a24=1.6666666666666666e-01;
  a25=pow(a23,a24);
  a26=(a25-a1);
  a27=(a9*a26);
  a27=(a1+a27);
  a28=casadi_sq(a25);
  a29=casadi_sq(a28);
  a30=(a25*a29);
  a30=(a30-a1);
  a31=(a9*a30);
  a31=(a1+a31);
  a32=(a27*a31);
  a22=(a22/a32);
  a33=sqrt(a22);
  a34=(a14*a33);
  a34=(a13-a34);
  if (res[0]!=0) res[0][0]=a34;
  a20=(a20+a20);
  a33=(a33+a33);
  a14=(a14/a33);
  a33=(a14/a32);
  a15=(a15*a33);
  a16=(a16*a15);
  a18=(a18*a16);
  a21=(a21+a21);
  a21=(a18/a21);
  a20=(a20*a21);
  a20=(a20+a18);
  a19=(a19*a20);
  a19=(a19-a16);
  if (res[1]!=0) res[1][0]=a19;
  a22=(a22/a32);
  a22=(a22*a14);
  a27=(a27*a22);
  a30=(a30*a27);
  a31=(a31*a22);
  a26=(a26*a31);
  a30=(a30+a26);
  a26=(a30/a13);
  a13=(a9/a13);
  a13=(a13*a30);
  a1=(a1-a13);
  a26=(a26+a1);
  a7=(a7*a26);
  if (res[1]!=0) res[1][1]=a7;
  a11=(a11*a1);
  if (res[1]!=0) res[1][2]=a11;
  a8=(a8*a26);
  a26=(a6*a8);
  a3=(a3*a26);
  a12=(a12*a1);
  a10=(a10*a12);
  a0=(a0*a10);
  a3=(a3-a0);
  if (res[1]!=0) res[1][3]=a3;
  a5=(a5*a8);
  a8=(a23/a6);
  a3=-8.3333333333333337e-01;
  a23=pow(a23,a3);
  a24=(a24*a23);
  a27=(a9*a27);
  a29=(a29*a27);
  a23=(a25+a25);
  a28=(a28+a28);
  a25=(a25*a27);
  a28=(a28*a25);
  a23=(a23*a28);
  a29=(a29+a23);
  a9=(a9*a31);
  a29=(a29+a9);
  a24=(a24*a29);
  a8=(a8*a24);
  a5=(a5-a8);
  if (res[1]!=0) res[1][4]=a5;
  a24=(a24/a6);
  a17=(a17*a33);
  a2=(a2*a17);
  a24=(a24-a2);
  a4=(a4*a12);
  a24=(a24+a4);
  if (res[1]!=0) res[1][5]=a24;
  a24=0.;
  if (res[1]!=0) res[1][6]=a24;
  return 0;
}

CASADI_SYMBOL_EXPORT int mwv1_choke_simpson_concave(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f7(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int mwv1_choke_simpson_concave_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int mwv1_choke_simpson_concave_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void mwv1_choke_simpson_concave_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int mwv1_choke_simpson_concave_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void mwv1_choke_simpson_concave_release(int mem) {
}

CASADI_SYMBOL_EXPORT void mwv1_choke_simpson_concave_incref(void) {
}

CASADI_SYMBOL_EXPORT void mwv1_choke_simpson_concave_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int mwv1_choke_simpson_concave_n_in(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_int mwv1_choke_simpson_concave_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real mwv1_choke_simpson_concave_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* mwv1_choke_simpson_concave_name_in(casadi_int i) {
  switch (i) {
    case 0: return "x";
    case 1: return "P";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* mwv1_choke_simpson_concave_name_out(casadi_int i) {
  switch (i) {
    case 0: return "g";
    case 1: return "J_x";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* mwv1_choke_simpson_concave_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* mwv1_choke_simpson_concave_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s7;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int mwv1_choke_simpson_concave_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* mwv1_choke_bernoulli_linear:(x[7],P[19])->(g,J_x[1x7]) */
static int casadi_f8(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a3, a4, a5, a6, a7, a8, a9;
  a0=3.1415926535897931e+00;
  a1=arg[1]? arg[1][1] : 0;
  a2=2.;
  a3=(a1/a2);
  a3=casadi_sq(a3);
  a3=(a0*a3);
  a4=arg[0]? arg[0][3] : 0;
  a5=(a3*a4);
  a6=arg[0]? arg[0][4] : 0;
  a7=(a5*a6);
  a8=arg[0]? arg[0][1] : 0;
  a9=(a7*a8);
  a1=(a1/a2);
  a1=casadi_sq(a1);
  a0=(a0*a1);
  a1=1.;
  a10=(a1-a4);
  a10=(a0*a10);
  a11=arg[0]? arg[0][5] : 0;
  a12=(a10*a11);
  a13=arg[0]? arg[0][2] : 0;
  a14=(a12*a13);
  a9=(a9+a14);
  a14=arg[1]? arg[1][11] : 0;
  a15=arg[1]? arg[1][17] : 0;
  a14=(a14*a15);
  a15=(a4*a6);
  a1=(a1-a4);
  a16=(a1*a11);
  a15=(a15+a16);
  a15=(a2*a15);
  a16=100000.;
  a17=arg[0]? arg[0][0] : 0;
  a18=5.0000000000000000e-01;
  a19=arg[1]? arg[1][12] : 0;
  a20=(a19*a17);
  a21=arg[1]? arg[1][14] : 0;
  a22=(a20+a21);
  a20=(a20-a21);
  a21=casadi_sq(a20);
  a23=9.9999999999999995e-07;
  a21=(a21+a23);
  a21=sqrt(a21);
  a22=(a22+a21);
  a22=(a18*a22);
  a17=(a17-a22);
  a17=(a16*a17);
  a22=(a15*a17);
  a22=sqrt(a22);
  a23=(a14*a22);
  a9=(a9-a23);
  if (res[0]!=0) res[0][0]=a9;
  a20=(a20+a20);
  a22=(a22+a22);
  a14=(a14/a22);
  a15=(a15*a14);
  a16=(a16*a15);
  a18=(a18*a16);
  a21=(a21+a21);
  a21=(a18/a21);
  a20=(a20*a21);
  a20=(a20+a18);
  a19=(a19*a20);
  a19=(a19-a16);
  if (res[1]!=0) res[1][0]=a19;
  if (res[1]!=0) res[1][1]=a7;
  if (res[1]!=0) res[1][2]=a12;
  a17=(a17*a14);
  a2=(a2*a17);
  a17=(a11*a2);
  a14=(a6*a2);
  a17=(a17-a14);
  a11=(a11*a13);
  a0=(a0*a11);
  a17=(a17-a0);
  a6=(a6*a8);
  a3=(a3*a6);
  a17=(a17+a3);
  if (res[1]!=0) res[1][3]=a17;
  a5=(a5*a8);
  a4=(a4*a2);
  a5=(a5-a4);
  if (res[1]!=0) res[1][4]=a5;
  a10=(a10*a13);
  a1=(a1*a2);
  a10=(a10-a1);
  if (res[1]!=0) res[1][5]=a10;
  a10=0.;
  if (res[1]!=0) res[1][6]=a10;
  return 0;
}

CASADI_SYMBOL_EXPORT int mwv1_choke_bernoulli_linear(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f8(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int mwv1_choke_bernoulli_linear_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int mwv1_choke_bernoulli_linear_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void mwv1_choke_bernoulli_linear_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int mwv1_choke_bernoulli_linear_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void mwv1_choke_bernoulli_linear_release(int mem) {
}

CASADI_SYMBOL_EXPORT void mwv1_choke_bernoulli_linear_incref(void) {
}

CASADI_SYMBOL_EXPORT void mwv1_choke_bernoulli_linear_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int mwv1_choke_bernoulli_linear_n_in(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_int mwv1_choke_bernoulli_linear_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real mwv1_choke_bernoulli_linear_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* mwv1_choke_bernoulli_linear_name_in(casadi_int i) {
  switch (i) {
    case 0: return "x";
    case 1: return "P";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* mwv1_choke_bernoulli_linear_name_out(casadi_int i) {
  switch (i) {
    case 0: return "g";
    case 1: return "J_x";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* mwv1_choke_bernoulli_linear_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* mwv1_choke_bernoulli_linear_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s7;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int mwv1_choke_bernoulli_linear_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* mwv1_choke_bernoulli_sigmoid:(x[7],P[19])->(g,J_x[1x7]) */
static int casadi_f9(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a3, a4, a5, a6, a7, a8, a9;
  a0=3.1415926535897931e+00;
  a1=arg[1]? arg[1][1] : 0;
  a2=2.;
  a3=(a1/a2);
  a3=casadi_sq(a3);
  a3=(a0*a3);
  a4=arg[0]? arg[0][3] : 0;
  a5=(a3*a4);
  a6=arg[0]? arg[0][4] : 0;
  a7=(a5*a6);
  a8=arg[0]? arg[0][1] : 0;
  a9=(a7*a8);
  a1=(a1/a2);
  a1=casadi_sq(a1);
  a0=(a0*a1);
  a1=1.;
  a10=(a1-a4);
  a10=(a0*a10);
  a11=arg[0]? arg[0][5] : 0;
  a12=(a10*a11);
  a13=arg[0]? arg[0][2] : 0;
  a14=(a12*a13);
  a9=(a9+a14);
  a14=arg[1]? arg[1][11] : 0;
  a15=arg[1]? arg[1][17] : 0;
  a16=1.5000000000000000e+00;
  a17=pow(a15,a16);
  a18=pow(a15,a16);
  a15=(a1-a15);
  a15=pow(a15,a16);
  a18=(a18+a15);
  a17=(a17/a18);
  a14=(a14*a17);
  a17=(a4*a6);
  a1=(a1-a4);
  a18=(a1*a11);
  a17=(a17+a18);
  a17=(a2*a17);
  a18=100000.;
  a15=arg[0]? arg[0][0] : 0;
  a16=5.0000000000000000e-01;
  a19=arg[1]? arg[1][12] : 0;
  a20=(a19*a15);
  a21=arg[1]? arg[1][14] : 0;
  a22=(a20+a21);
  a20=(a20-a21);
  a21=casadi_sq(a20);
  a23=9.9999999999999995e-07;
  a21=(a21+a23);
  a21=sqrt(a21);
  a22=(a22+a21);
  a22=(a16*a22);
  a15=(a15-a22);
  a15=(a18*a15);
  a22=(a17*a15);
  a22=sqrt(a22);
  a23=(a14*a22);
  a9=(a9-a23);
  if (res[0]!=0) res[0][0]=a9;
  a20=(a20+a20);
  a22=(a22+a22);
  a14=(a14/a22);
  a17=(a17*a14);
  a18=(a18*a17);
  a16=(a16*a18);
  a21=(a21+a21);
  a21=(a16/a21);
  a20=(a20*a21);
  a20=(a20+a16);
  a19=(a19*a20);
  a19=(a19-a18);
  if (res[1]!=0) res[1][0]=a19;
  if (res[1]!=0) res[1][1]=a7;
  if (res[1]!=0) res[1][2]=a12;
  a15=(a15*a14);
  a2=(a2*a15);
  a15=(a11*a2);
  a14=(a6*a2);
  a15=(a15-a14);
  a11=(a11*a13);
  a0=(a0*a11);
  a15=(a15-a0);
  a6=(a6*a8);
  a3=(a3*a6);
  a15=(a15+a3);
  if (res[1]!=0) res[1][3]=a15;
  a5=(a5*a8);
  a4=(a4*a2);
  a5=(a5-a4);
  if (res[1]!=0) res[1][4]=a5;
  a10=(a10*a13);
  a1=(a1*a2);
  a10=(a10-a1);
  if (res[1]!=0) res[1][5]=a10;
  a10=0.;
  if (res[1]!=0) res[1][6]=a10;
  return 0;
}

CASADI_SYMBOL_EXPORT int mwv1_choke_bernoulli_sigmoid(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f9(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int mwv1_choke_bernoulli_sigmoid_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int mwv1_choke_bernoulli_sigmoid_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void mwv1_choke_bernoulli_sigmoid_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int mwv1_choke_bernoulli_sigmoid_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void mwv1_choke_bernoulli_sigmoid_release(int mem) {
}

CASADI_SYMBOL_EXPORT void mwv1_choke_bernoulli_sigmoid_incref(void) {
}

CASADI_SYMBOL_EXPORT void mwv1_choke_bernoulli_sigmoid_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int mwv1_choke_bernoulli_sigmoid_n_in(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_int mwv1_choke_bernoulli_sigmoid_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real mwv1_choke_bernoulli_sigmoid_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* mwv1_choke_bernoulli_sigmoid_name_in(casadi_int i) {
  switch (i) {
    case 0: return "x";
    case 1: return "P";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* mwv1_choke_bernoulli_sigmoid_name_out(casadi_int i) {
  switch (i) {
    case 0: return "g";
    case 1: return "J_x";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* mwv1_choke_bernoulli_sigmoid_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* mwv1_choke_bernoulli_sigmoid_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s7;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int mwv1_choke_bernoulli_sigmoid_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* mwv1_choke_bernoulli_convex:(x[7],P[19])->(g,J_x[1x7]) */
static int casadi_f10(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a3, a4, a5, a6, a7, a8, a9;
  a0=3.1415926535897931e+00;
  a1=arg[1]? arg[1][1] : 0;
  a2=2.;
  a3=(a1/a2);
  a3=casadi_sq(a3);
  a3=(a0*a3);
  a4=arg[0]? arg[0][3] : 0;
  a5=(a3*a4);
  a6=arg[0]? arg[0][4] : 0;
  a7=(a5*a6);
  a8=arg[0]? arg[0][1] : 0;
  a9=(a7*a8);
  a1=(a1/a2);
  a1=casadi_sq(a1);
  a0=(a0*a1);
  a1=1.;
  a10=(a1-a4);
  a10=(a0*a10);
  a11=arg[0]? arg[0][5] : 0;
  a12=(a10*a11);
  a13=arg[0]? arg[0][2] : 0;
  a14=(a12*a13);
  a9=(a9+a14);
  a14=arg[1]? arg[1][11] : 0;
  a15=2.5000000000000000e-01;
  a16=arg[1]? arg[1][17] : 0;
  a15=(a15*a16);
  a17=7.5000000000000000e-01;
  a16=casadi_sq(a16);
  a17=(a17*a16);
  a15=(a15+a17);
  a14=(a14*a15);
  a15=(a4*a6);
  a1=(a1-a4);
  a17=(a1*a11);
  a15=(a15+a17);
  a15=(a2*a15);
  a17=100000.;
  a16=arg[0]? arg[0][0] : 0;
  a18=5.0000000000000000e-01;
  a19=arg[1]? arg[1][12] : 0;
  a20=(a19*a16);
  a21=arg[1]? arg[1][14] : 0;
  a22=(a20+a21);
  a20=(a20-a21);
  a21=casadi_sq(a20);
  a23=9.9999999999999995e-07;
  a21=(a21+a23);
  a21=sqrt(a21);
  a22=(a22+a21);
  a22=(a18*a22);
  a16=(a16-a22);
  a16=(a17*a16);
  a22=(a15*a16);
  a22=sqrt(a22);
  a23=(a14*a22);
  a9=(a9-a23);
  if (res[0]!=0) res[0][0]=a9;
  a20=(a20+a20);
  a22=(a22+a22);
  a14=(a14/a22);
  a15=(a15*a14);
  a17=(a17*a15);
  a18=(a18*a17);
  a21=(a21+a21);
  a21=(a18/a21);
  a20=(a20*a21);
  a20=(a20+a18);
  a19=(a19*a20);
  a19=(a19-a17);
  if (res[1]!=0) res[1][0]=a19;
  if (res[1]!=0) res[1][1]=a7;
  if (res[1]!=0) res[1][2]=a12;
  a16=(a16*a14);
  a2=(a2*a16);
  a16=(a11*a2);
  a14=(a6*a2);
  a16=(a16-a14);
  a11=(a11*a13);
  a0=(a0*a11);
  a16=(a16-a0);
  a6=(a6*a8);
  a3=(a3*a6);
  a16=(a16+a3);
  if (res[1]!=0) res[1][3]=a16;
  a5=(a5*a8);
  a4=(a4*a2);
  a5=(a5-a4);
  if (res[1]!=0) res[1][4]=a5;
  a10=(a10*a13);
  a1=(a1*a2);
  a10=(a10-a1);
  if (res[1]!=0) res[1][5]=a10;
  a10=0.;
  if (res[1]!=0) res[1][6]=a10;
  return 0;
}

CASADI_SYMBOL_EXPORT int mwv1_choke_bernoulli_convex(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f10(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int mwv1_choke_bernoulli_convex_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int mwv1_choke_bernoulli_convex_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void mwv1_choke_bernoulli_convex_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int mwv1_choke_bernoulli_convex_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void mwv1_choke_bernoulli_convex_release(int mem) {
}

CASADI_SYMBOL_EXPORT void mwv1_choke_bernoulli_convex_incref(void) {
}

CASADI_SYMBOL_EXPORT void mwv1_choke_bernoulli_convex_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int mwv1_choke_bernoulli_convex_n_in(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_int mwv1_choke_bernoulli_convex_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real mwv1_choke_bernoulli_convex_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* mwv1_choke_bernoulli_convex_name_in(casadi_int i) {
  switch (i) {
    case 0: return "x";
    case 1: return "P";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* mwv1_choke_bernoulli_convex_name_out(casadi_int i) {
  switch (i) {
    case 0: return "g";
    case 1: return "J_x";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* mwv1_choke_bernoulli_convex_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* mwv1_choke_bernoulli_convex_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s7;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int mwv1_choke_bernoulli_convex_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* mwv1_choke_bernoulli_concave:(x[7],P[19])->(g,J_x[1x7]) */
static int casadi_f11(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a3, a4, a5, a6, a7, a8, a9;
  a0=3.1415926535897931e+00;
  a1=arg[1]? arg[1][1] : 0;
  a2=2.;
  a3=(a1/a2);
  a3=casadi_sq(a3);
  a3=(a0*a3);
  a4=arg[0]? arg[0][3] : 0;
  a5=(a3*a4);
  a6=arg[0]? arg[0][4] : 0;
  a7=(a5*a6);
  a8=arg[0]? arg[0][1] : 0;
  a9=(a7*a8);
  a1=(a1/a2);
  a1=casadi_sq(a1);
  a0=(a0*a1);
  a1=1.;
  a10=(a1-a4);
  a10=(a0*a10);
  a11=arg[0]? arg[0][5] : 0;
  a12=(a10*a11);
  a13=arg[0]? arg[0][2] : 0;
  a14=(a12*a13);
  a9=(a9+a14);
  a14=arg[1]? arg[1][11] : 0;
  a15=arg[1]? arg[1][17] : 0;
  a16=7.5000000000000000e-01;
  a15=pow(a15,a16);
  a14=(a14*a15);
  a15=(a4*a6);
  a1=(a1-a4);
  a16=(a1*a11);
  a15=(a15+a16);
  a15=(a2*a15);
  a16=100000.;
  a17=arg[0]? arg[0][0] : 0;
  a18=5.0000000000000000e-01;
  a19=arg[1]? arg[1][12] : 0;
  a20=(a19*a17);
  a21=arg[1]? arg[1][14] : 0;
  a22=(a20+a21);
  a20=(a20-a21);
  a21=casadi_sq(a20);
  a23=9.9999999999999995e-07;
  a21=(a21+a23);
  a21=sqrt(a21);
  a22=(a22+a21);
  a22=(a18*a22);
  a17=(a17-a22);
  a17=(a16*a17);
  a22=(a15*a17);
  a22=sqrt(a22);
  a23=(a14*a22);
  a9=(a9-a23);
  if (res[0]!=0) res[0][0]=a9;
  a20=(a20+a20);
  a22=(a22+a22);
  a14=(a14/a22);
  a15=(a15*a14);
  a16=(a16*a15);
  a18=(a18*a16);
  a21=(a21+a21);
  a21=(a18/a21);
  a20=(a20*a21);
  a20=(a20+a18);
  a19=(a19*a20);
  a19=(a19-a16);
  if (res[1]!=0) res[1][0]=a19;
  if (res[1]!=0) res[1][1]=a7;
  if (res[1]!=0) res[1][2]=a12;
  a17=(a17*a14);
  a2=(a2*a17);
  a17=(a11*a2);
  a14=(a6*a2);
  a17=(a17-a14);
  a11=(a11*a13);
  a0=(a0*a11);
  a17=(a17-a0);
  a6=(a6*a8);
  a3=(a3*a6);
  a17=(a17+a3);
  if (res[1]!=0) res[1][3]=a17;
  a5=(a5*a8);
  a4=(a4*a2);
  a5=(a5-a4);
  if (res[1]!=0) res[1][4]=a5;
  a10=(a10*a13);
  a1=(a1*a2);
  a10=(a10-a1);
  if (res[1]!=0) res[1][5]=a10;
  a10=0.;
  if (res[1]!=0) res[1][6]=a10;
  return 0;
}

CASADI_SYMBOL_EXPORT int mwv1_choke_bernoulli_concave(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f11(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int mwv1_choke_bernoulli_concave_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int mwv1_choke_bernoulli_concave_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void mwv1_choke_bernoulli_concave_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int mwv1_choke_bernoulli_concave_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void mwv1_choke_bernoulli_concave_release(int mem) {
}

CASADI_SYMBOL_EXPORT void mwv1_choke_bernoulli_concave_incref(void) {
}

CASADI_SYMBOL_EXPORT void mwv1_choke_bernoulli_concave_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int mwv1_choke_bernoulli_concave_n_in(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_int mwv1_choke_bernoulli_concave_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real mwv1_choke_bernoulli_concave_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* mwv1_choke_bernoulli_concave_name_in(casadi_int i) {
  switch (i) {
    case 0: return "x";
    case 1: return "P";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* mwv1_choke_bernoulli_concave_name_out(casadi_int i) {
  switch (i) {
    case 0: return "g";
    case 1: return "J_x";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* mwv1_choke_bernoulli_concave_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* mwv1_choke_bernoulli_concave_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s7;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int mwv1_choke_bernoulli_concave_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
